# Generated by Django 5.0.4 on 2024-05-07 13:16

import django.core.validators
import django.db.models.deletion
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('user_name', models.CharField(help_text='Insira seu nome completo. Ex.: João Santos Silva', max_length=30, validators=[django.core.validators.RegexValidator(re.compile(''), 'Insira um nome válido', 'Inválido')], verbose_name='Nome')),
                ('cpf', models.CharField(help_text='XXX.XXX.XXX-XX', max_length=30, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^(?:[0-9]{3}[\\.|-]){3}[0-9]{2}$'), 'Insira um número válido', 'Inválido')], verbose_name='CPF')),
                ('is_active', models.BooleanField(default=True, help_text='Denota se o usuário está ou não ativo. Possível desativar cammpo ao invés de deletar o usuário', verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, help_text='Denota se o usuário é ou não um Colaborador.', verbose_name='Colaborador')),
                ('is_trusty', models.BooleanField(default=False, help_text='Denota se o usuário confirmou seu email', verbose_name='Validado')),
                ('is_psicologist', models.BooleanField(default=False)),
                ('is_patient', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Data de criação do usuário no banco de dados.', verbose_name='Data de criação')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phonenumber', models.CharField(help_text='Ex.: (XX)XXXX-XXXX', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\([0-9]{2}\\)[0-9]{4,5}-[0-9]{4}$'), 'Insira um número válido', 'Inválido')], verbose_name='Número de telefone')),
                ('address', models.CharField(help_text='Ex.: Rua/Av. XXX, NºXX, Complemento (se houver) - Bairro, Cidade, Estado - CEP', max_length=30, unique=True, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('crp', models.CharField(help_text='XX/XXXXXX', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]{2}\\/[0-9]{6}$'), 'Insira um número válido', 'Inválido')], verbose_name='CRP')),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patients')),
            ],
            options={
                'verbose_name': 'Psicólogo',
                'verbose_name_plural': 'Psicólogos',
            },
        ),
    ]
