# Generated by Django 5.1.3 on 2024-12-08 11:46

import appsico_app.models
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('phonenumber', models.CharField(help_text='Ex.: (XX)XXXX-XXXX', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\([0-9]{2}\\)[0-9]{4,5}-[0-9]{4}$'), 'Insira um número válido', 'Inválido')], verbose_name='Número de telefone')),
                ('user_name', models.CharField(help_text='Insira seu nome completo. Ex.: João Santos Silva', max_length=30, validators=[django.core.validators.RegexValidator(re.compile(''), 'Insira um nome válido', 'Inválido')], verbose_name='Nome')),
                ('cpf', models.CharField(help_text='XXX.XXX.XXX-XX', max_length=30, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^(?:[0-9]{3}[\\.|-]){3}[0-9]{2}$'), 'Insira um número válido', 'Inválido')], verbose_name='CPF')),
                ('crp', models.CharField(help_text='XX/XXXXXX', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]{2}\\/[0-9]{6}$'), 'Insira um número válido', 'Inválido')], verbose_name='CRP')),
                ('is_patient', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Psicólogo',
                'verbose_name_plural': 'Psicólogos',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('phonenumber', models.CharField(help_text='Ex.: (XX)XXXX-XXXX', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\([0-9]{2}\\)[0-9]{4,5}-[0-9]{4}$'), 'Insira um número válido', 'Inválido')], verbose_name='Número de telefone')),
                ('address', models.CharField(help_text='Ex.: Rua/Av. XXX, NºXX, Complemento (se houver) - Bairro, Cidade, Estado - CEP', max_length=30, unique=True, verbose_name='Endereço')),
                ('user_name', models.CharField(help_text='Insira seu nome completo. Ex.: João Santos Silva', max_length=30, validators=[django.core.validators.RegexValidator(re.compile(''), 'Insira um nome válido', 'Inválido')], verbose_name='Nome')),
                ('cpf', models.CharField(help_text='XXX.XXX.XXX-XX', max_length=30, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^(?:[0-9]{3}[\\.|-]){3}[0-9]{2}$'), 'Insira um número válido', 'Inválido')], verbose_name='CPF')),
                ('is_psicologist', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('user_name', models.CharField(help_text='Insira seu nome completo. Ex.: João Santos Silva', max_length=30, validators=[django.core.validators.RegexValidator(re.compile(''), 'Insira um nome válido', 'Inválido')], verbose_name='Nome')),
                ('cpf', models.CharField(help_text='XXX.XXX.XXX-XX', max_length=30, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^(?:[0-9]{3}[\\.|-]){3}[0-9]{2}$'), 'Insira um número válido', 'Inválido')], verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Recepcção',
                'verbose_name_plural': 'Recepção',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.TextField(verbose_name='Relatório')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Data de criação da entrada no prontuário', verbose_name='Criado em: ')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsico_app.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsico_app.patients')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactions_status', models.CharField(choices=[(appsico_app.models.TRANSACTIONS_STATUS['PAYED'], 'Processo finalizado: Pago.'), (appsico_app.models.TRANSACTIONS_STATUS['IN_PAYMENT'], 'Boleto gerado e enviado para pagamento'), (appsico_app.models.TRANSACTIONS_STATUS['START_PROCESS'], 'Boleto a ser gerado')], help_text='Como estão as Transações', max_length=80, verbose_name='Transações')),
                ('user_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsico_app.patients')),
            ],
            options={
                'verbose_name': 'Finança',
                'verbose_name_plural': 'Finanças',
            },
        ),
        migrations.AddField(
            model_name='doctors',
            name='patient_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsico_app.patients'),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('data', models.DateField()),
                ('cpf_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsico_app.patients')),
            ],
            options={
                'verbose_name': 'Calendário',
                'verbose_name_plural': 'Calendários',
            },
        ),
    ]
