# Generated by Django 5.0.4 on 2024-05-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.TextField(verbose_name='Entrada')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Data de criação da entrada no prontuário', verbose_name='Criado em: ')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
            },
        ),
    ]
