# Generated by Django 5.1.3 on 2024-12-08 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsico_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_psicologist',
            new_name='is_psychologist',
        ),
    ]
